version: '3'
services:
  tachyonic:
    image: "tachyonic"
    ports:
     - "80:80"
    volumes:
     -  ./tachyonic/tachyonic:/usr/local/lib/python3.5/dist-packages/tachyonic/tachyonic
     -  ./tachyonic_neutrino/tachyonic/neutrino:/usr/local/lib/python3.5/dist-packages/tachyonic/neutrino
     -  ./tachyonic_api/tachyonic/api:/usr/local/lib/python3.5/dist-packages/tachyonic/api
     -  ./tachyonic_ui/tachyonic/ui:/usr/local/lib/python3.5/dist-packages/tachyonic/ui
